version: '3'

services:
  app:
    build: .
    container_name: api_server
    ports:
      - "8080:5000"
    volumes:
      - ./app:/usr/app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py